package edu.cnm.deepdive.testquestions;

import java.io.FileNotFoundException;
import java.io.IOException;

public class ExceptionExample {

/*  public static void main(String[] args) {
    try {
      method();
    } catch (IOException e) {
      System.out.println("caught");
    }

  }

  public static IOException method(){
    try {
      return new IOException();

    } catch (FileNotFoundException e) {
      return new FileNotFoundException();
    }
  }*/

  //lines 11 and 21 will not compile in the catch block because those exception declaration cannot be added there.
}
